Repository ForesightMiningSoftwareCorporation/fslabscli, pull requests merged in 2025-04, with the labels that each got.

#125 publish: tag current commit for every package published
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
Labels: size/XL, approved

#126 chore: add logging to ssh, and default
  src/utils/mod.rs
Labels: approved, size/XS

#130 feat: set cargo_main_registry
  Cargo.lock
  Cargo.toml
  src/commands/check_workspace/mod.rs
  src/commands/publish/mod.rs
  src/utils/mod.rs
Labels: approved, size/M

#134 chore: always cross individualPackages
  flake.nix
Labels: size/S, approved

#136 fslabscli can self-update
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/utils/auto_update.rs
  src/utils/mod.rs
Labels: size/L, approved

#138 chore: switch to rusttls
  Cargo.lock
  Cargo.toml
Labels: size/L, approved

#140 restore metrics temporality
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: size/S, approved

#143 disable colors in logs on commands
  src/utils/mod.rs
Labels: approved, size/XS

#146 getting auto-update to work in CI
  src/main.rs
  src/utils/auto_update.rs
Labels: approved, size/M

#150 display total duration of tests
  Cargo.lock
  Cargo.toml
  src/commands/tests/mod.rs
Labels: size/S, approved

#160 find the most specific crate modified by a change
  src/crate_graph.rs
Labels: approved, size/M

#161 chore: restore summaries command
  Cargo.toml
  flake.nix
  src/commands/mod.rs
  src/commands/summaries/mod.rs
  src/commands/summaries/run_types/checks.rs
  src/commands/summaries/run_types/mod.rs
  src/commands/summaries/run_types/publishing.rs
  src/commands/summaries/template/mod.rs
  src/main.rs
Labels: approved

#162 fix: add missing tag option
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
Labels: approved, size/XS

#166 feat: allow tests to be skip
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
  src/commands/summaries/mod.rs
  src/commands/summaries/run_types/checks.rs
  src/commands/summaries/run_types/mod.rs
  src/commands/summaries/run_types/publishing.rs
  src/commands/tests/mod.rs
Labels: approved, size/M
