Repository ForesightMiningSoftwareCorporation/fslabscli, pull requests merged in 2025-02, with the labels that each got.

#63 feat: log why packages are being tested
  Cargo.toml
  src/commands/check_workspace/mod.rs
Labels: approved, size/XS

#65 chore: add more logs for debugging CI
  Cargo.lock
  Cargo.toml
  src/commands/check_workspace/mod.rs
Labels: size/XS

#64 fix: remove default features from reqwest
  Cargo.lock
  Cargo.toml
  flake.lock
  rustfmt.toml
  src/commands/docker_build_push/mod.rs
Labels: size/XXL

#61 chore: resetup updatecli and remove github actions
  .github/workflows/matrix.json
  .github/workflows/release-publish.yml
  .github/workflows/tests.yml
  .github/workflows/update_pre_commit.yml
  updatecli-compose.yaml
  updatecli/updatecli.d/.gitkeep
  updatecli/values.d/scm.yaml
  updatecli/values.d/updatecli-compose.yaml
Labels: size/L

#66 feat: log tests args
  src/commands/docker_build_push/mod.rs
  src/commands/rust_tests/mod.rs
Labels: approved, size/XS

#67 feat: send log to stderr
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: approved, size/XS, tide/merge-method-rebase

#68 feat: remove all optional tests
  Cargo.lock
  Cargo.toml
  src/commands/rust_tests/mod.rs
Labels: size/M

#69 fix: docker context should be set
  Cargo.lock
  Cargo.toml
  src/commands/docker_build_push/mod.rs
Labels: approved, size/XS

#71 chore: add code owner for prow
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/M

#73 chore: dump bump to test release-drafter
  Cargo.lock
  Cargo.toml
Labels: approved, size/XS
