Repository ForesightMiningSoftwareCorporation/fslabscli, pull requests merged in 2025-03, with the labels that each got.

#87 feat: move to otel collector
  Cargo.lock
  Cargo.toml
  src/commands/check_workspace/cargo.rs
  src/commands/check_workspace/docker.rs
  src/commands/check_workspace/mod.rs
  src/commands/check_workspace/npm.rs
  src/commands/docker_build_push/mod.rs
  src/commands/generate_wix/mod.rs
  src/commands/rust_tests/mod.rs
  src/main.rs
Labels: size/XL, approved

#88 fix: add new line to junit export
  Cargo.lock
  Cargo.toml
  src/commands/rust_tests/mod.rs
Labels: approved, size/XS

#97 feat: less log but better log
  Cargo.lock
  Cargo.toml
  src/commands/check_workspace/cargo.rs
  src/commands/check_workspace/mod.rs
  src/commands/publish/mod.rs
  src/utils/mod.rs
Labels: size/S, approved

#102 feat: add docker publishing and better piublish log formatting
  .gitignore
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
Labels: size/XL, approved

#104 fix: ensure additional script output is shown
  Cargo.toml
  src/commands/rust_tests/mod.rs
Labels: size/M

#105 Renama rust tests
  Cargo.lock
  Cargo.toml
  flake.nix
  src/commands/mod.rs
  src/commands/summaries/mod.rs
  src/commands/summaries/run_types/checks.rs
  src/commands/summaries/run_types/mod.rs
  src/commands/summaries/run_types/publishing.rs
  src/commands/summaries/template/mod.rs
  src/commands/tests/mod.rs
  src/main.rs
Labels: size/XXL

#110 fix: replace in all workspace, for workspace deps
  Cargo.lock
  Cargo.toml
  src/commands/publish/mod.rs
  src/utils/cargo.rs
Labels: size/M

#114 fix: sub_failed check was backwards
  Cargo.lock
  Cargo.toml
  src/commands/tests/mod.rs
Labels: approved, size/XS

#117 feat: add cycle detection
  Cargo.lock
  Cargo.toml
  src/commands/check_workspace/binary.rs
  src/commands/check_workspace/docker.rs
  src/commands/check_workspace/mod.rs
  src/commands/check_workspace/npm.rs
  src/commands/download_artifacts/mod.rs
  src/commands/fix_lock_files/mod.rs
  src/commands/generate_wix/mod.rs
  src/commands/generate_workflow/mod.rs
  src/commands/github_app_token/mod.rs
  src/commands/publish/mod.rs
  src/commands/tests/mod.rs
  src/crate_graph.rs
  src/main.rs
  src/utils/cargo.rs
  src/utils/github.rs
  src/utils/mod.rs
  src/utils/test.rs
Labels: size/L, approved

#119 feat: simplify and update nix build
  flake.lock
  flake.nix
Labels: size/L, approved

#92 Test packages when their deps change.
  Cargo.toml
  src/commands/check_workspace/mod.rs
Labels: approved, size/XS
